# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tabeeb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tabeeb
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'MessageKit'
pod 'UICircularProgressRing'
pod 'JGProgressHUD'



  target 'TabeebTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabeebUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
