# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'Tabeeb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for Tabeeb
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'MessageKit'
pod 'UICircularProgressRing'
pod 'JGProgressHUD'
pod 'OpenTok'

  pod 'OneSignal'

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignal'
end



  target 'TabeebTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabeebUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end

end

